### ISSUE TITLE
CHANGELOG unmaintained?

### ISSUE THREAD

**Issue by zacstewart** [jonathanKingston/ember-cli-sri#19]
I have a project sitting on ember-cli-sri 1.2.1. While upgrading dependencies, I noticed that this one was behind a major version. I wanted to check the CHANGELOG to see if there were any changes I needed to be aware of, but unfortunately the most recent update appears to have been made for version 1.1.0.

**Comment by jonathanKingston** [comment]
Sure, I'll add it as a task for the next release. The changes are not particularly substantial anyway here is what I can remember (feel free to look through the commits manually and prove me wrong):

- Adding in use of broccoli-caching-writer to improve perf
- broccoli-sri-hash removed the default of paranoiaCheck which was checking for unicode chars
- improve build testing etc

**Comment by zacstewart** [comment]
:+1: Thanks!

**Comment by jonathanKingston** [comment]
Was fixed
