### ISSUE TITLE
Integrity hash failing with chrome data saver enabled

### ISSUE THREAD

**Issue by thagul** [jonathanKingston/ember-cli-sri#26]
If I enable Chrome Data Saver on android devices or on desktop (using addon https://chrome.google.com/webstore/detail/data-saver/pfmgfdlgomnbgkofeojodiodmgpgmkac) I always get error

`Failed to find a valid digest in the 'integrity' attribute for resource xxxx with computed SHA-256 integrity 'SNNv36qc62jtyjezdcQqCKm3i+2javQMi3Gi4RVrw2E='. The resource has been blocked.`

I didn't added anything to `ember-cli-build.js` file regarding SRI configuration but if I disable SRI everything works fine.

```
SRI: {
      enabled: false
    }
```

I'm using 
ember-cli: 2.6.2
ember-cli-sri: ^2.1.0
ember.js: ~2.6.0

**Comment by vividh-furlenco** [comment]
Yes, happening for me too.
----
Ember      : 2.5.1
Ember Data : 2.7.0
----

Disabling SRI worked for me too. I am not using a CDN for the assets currently.

**Comment by jonathanKingston** [comment]
This is a bug with Google and not this. They are not ruling out SRI assets which is a real shame here.

**Comment by jonathanKingston** [comment]
Closing as won't fix. Will try and contact the addon makers.

**Comment by jonathanKingston** [comment]
Adding HTTPs on your production servers should mitigate this they suggest they will only enable this on HTTP assets.

**Comment by thagul** [comment]
Thanks @jonathanKingston, I will enable https soon or later on production, in the meanwhile I've completely disabled sri
