### ISSUE TITLE
Acceptance test output in main file

### ISSUE THREAD

**Issue by jonathanKingston** [jonathanKingston/ember-cli-sri#4]
Acceptance test output is found in the main file; I think this is due to the change in Brocfile usage however needs investigation.

Relates to this comment: https://github.com/jonathanKingston/ember-cli-sri/issues/2#issuecomment-135501374

**Comment by jonathanKingston** [comment]
@Keeo this has now resolved in the latest 1.0.4 release. However that will unlikely fix your issue that you mentioned. I suspect that is an encoding issue. Could you retest please?

**Comment by Keeo** [comment]
Thanks for creating issue for me. It may be possible since I changed environment recently. I will look into it.

**Comment by Keeo** [comment]
That was pain to find but I finally got it. Project was indeed poisoned with win-1250 encoding, but fixing that doesn't fixed the problem. 
After diffing my project with clean one I found out that problem is causing [moment](https://github.com/moment/moment/) library included __with locales__. I made clean [repository](https://github.com/Keeo/ember-sri-moment/commit/610eba4d7901f8a0a00053852ffa300632553899) showcasing this issue.

**Comment by jonathanKingston** [comment]
The output I am getting for `ember build --env=production` are:

```
    <link rel="stylesheet" href="assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css" integrity="sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU= sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==" >
    <link rel="stylesheet" href="assets/ember-sri-moment-d41d8cd98f00b204e9800998ecf8427e.css" integrity="sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU= sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==" >
    <script src="assets/vendor-5421a7c30be1d14a5e49b2d44cd3e97f.js" integrity="sha256-WBl68hmGSYWBjMr7TTsGZi+9v8AGh/HVpwIXFmYxZO4= sha512-w7zjbLkStuQs9a+mRoATDaB9nmEiAnBiGeQ9X5RoYPV34dqcHArOYC/R+7DbY00oa5iRNrzl6JBqbUNwnIXETw==" ></script>
    <script src="assets/ember-sri-moment-ecff39730d01a0a7cc2dcf965387beab.js" integrity="sha256-G3oh7BewjqPE3eyuUqY4bCEDPOGt/AMKe8Of/9a+OYA= sha512-7psoL36Ppc+R279evAFZyE5EG05zbluT6h9psIc/4myamOUnbItLYh42s8AqlIIscxM7l0poL6TLDr3hJiAhng==" ></script>
```

This seems to be ok when comparing it to the toolbox I use which means there isn't a race condition in play here.

In Chrome 46 Linux this however fails too (reopening as a new issue as I think its likely fairly serious).
