### ISSUE TITLE
Adds integrity for all except `vendor.js`, `frontend.js` and `frontend.css`

### ISSUE THREAD

**Issue by YoranBrondsema** [jonathanKingston/ember-cli-sri#8]
Hi,

I enabled SRI according to the instructions. The weird thing is, it adds the integrity attribute for all stylesheets and scripts except for `vendor.js`, `frontend.js` and `frontend.css`. I'm not really sure why these are treated differently. Any idea?

Yoran

**Comment by jonathanKingston** [comment]
See: #5

Chrome encoding is breaking unicode sometimes; the code doesn't work on
those files to prevent breaking for now.

**Comment by YoranBrondsema** [comment]
OK I see, that choice makes sense. Thanks for the quick reply!

**Comment by jonathanKingston** [comment]
Closing as #5 is a better issue for this and the Chrome team is working on this. (Thank you for checking here :+1: )
